# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata: 
    name: deployment-p5capstone
spec:
    # https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
    type: LoadBalancer
    selector:
        app: deployment-p5capstone
    ports:
        - name: http
          protocol: TCP
          port: 8000
          targetPort: 80
